-- ALTERATIONS FOR EXISTING DATABASE
ALTER TABLE users ADD COLUMN IF NOT EXISTS fcm_token VARCHAR(255);

ALTER TABLE assessment_attempts ADD COLUMN IF NOT EXISTS total_score INT DEFAULT 0;
ALTER TABLE assessment_attempts ADD COLUMN IF NOT EXISTS violations INT DEFAULT 0;

ALTER TABLE user_answers ADD COLUMN IF NOT EXISTS is_correct BOOLEAN;

-- NOTIFICATION HISTORY
CREATE TABLE IF NOT EXISTS notification_history (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(200),
  body TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ASSIGNED BADGES
CREATE TABLE IF NOT EXISTS assigned_badges (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  architect_id UUID REFERENCES users(id) ON DELETE SET NULL,
  badge_name VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
